# 配置端口
server:
  port: 3333
spring:
  application:
    name: ShiroApiCode
  profiles:
    active: test  # prod生产 dev开发   dev开发|test测试|prod生产
  # 配置数据源
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wlq?useUnicode=true&characterEncoding=utf-8&useSSL=false

#mybatis:
#  config-location=classpath: /mybatis-config.xml
#  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
#    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




